server:
  port: 8082
spring:
  application:
    name: Eureka-client2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
